services:
  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile
      args:
        UID: 1000
        GID: 1000
    # Mount the current directory into the container
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "81:80"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: remote_enable=1 remote_autostart=1 remote_host=host.docker.internal
    #      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-api_db}
      MYSQL_USER: ${MYSQL_USER:-api_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
